[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

# ✅ SPA routing fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ✅ API proxying to FastAPI backend
[[redirects]]
  from = "/api/*"
  to = "http://127.0.0.1:8000/:splat"
  status = 200
  force = true

# ✅ WebSocket proxying
[[redirects]]
  from = "/ws/*"
  to = "ws://127.0.0.1:8000/:splat"
  status = 200
  force = true
