[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

# ✅ SPA routing fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

