[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "aria-backend"

[services.variables]
PORT = "8000"
PYTHONPATH = "/app"
REDIS_URL = "${{Redis.REDIS_URL}}"
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
